-- ststat Supabase 전체 설정(한 파일)
--
-- Supabase SQL 편집기에 이 파일 전체를 붙여 넣고 실행한다. 여러 번 실행해도 된다:
--   표·열·인덱스는 없을 때만 만들고, 함수·뷰·정책·권한은 최신으로 다시 쓴다. 운영 데이터는 바꾸지 않는다.
-- StarUniv/Synergy가 함께 쓰는 DB다. StarUniv 기본 표(tier_members·elo_*·matches·rounds·videos,
-- is_admin 등)는 staruniv 저장소 supabase/staruniv.sql이 만들므로 그 파일을 먼저 실행한다.
-- (예전 migrations/001~012를 순서대로 합쳤다. 012가 대신하는 010과 이미 끝난 일회성 데이터 채우기는 뺐다.)
--
-- 구성(순서대로):
--   1 작업 기록 → 2 선수 후보 대기열 → 3 EloBoard 수집 보강 → 4 EloBoard 파생 통계(스냅샷 교체)
--   → 5 시너지 월간·일별 방송 통계 → 6 영상 수집 → 7 경기·라운드 연결 점검 → 8 시너지 하루치 게시
--   → 9 StarUniv·Synergy 공개 조회 → 10 티어랭킹 v4(모든 선수 레이팅·종족 상성) → 11 어드민 운영 현황


-- ############################################################################
-- 1. 작업 기록(sync_jobs)
-- ############################################################################

create table if not exists public.sync_jobs (
    id bigint generated by default as identity primary key,
    job_name text not null,
    run_id text,
    status text not null check (status in ('running','success','failed','skipped')),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    records_read integer not null default 0,
    records_written integer not null default 0,
    records_skipped integer not null default 0,
    error_message text,
    source_cursor text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists sync_jobs_job_name_started_idx
on public.sync_jobs (job_name, started_at desc);

alter table public.sync_jobs enable row level security;

-- sync_jobs is an internal operations table.
-- No anon/authenticated policies are created intentionally.
-- The ststat pipeline uses the Supabase service role key server-side only.


-- ############################################################################
-- 2. 선수 후보 대기열(tier_member_candidates)
-- ############################################################################

-- ststat Part 2: roster candidate staging.
-- Run once in the SAME Supabase project used by StarUniv/Synergy.
-- Safe to re-run.

create table if not exists public.tier_member_candidates (
  id text primary key,
  nickname text not null default '',
  elo_id integer,
  gender text,
  race text,
  tier text,
  affiliation text,
  source text,
  found_at date,
  status text not null default 'pending',
  last_seen_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tier_member_candidates
  add column if not exists status text not null default 'pending';
alter table public.tier_member_candidates
  add column if not exists last_seen_at date;
alter table public.tier_member_candidates
  add column if not exists updated_at timestamptz not null default now();

create index if not exists tier_member_candidates_elo_id_idx
  on public.tier_member_candidates (elo_id);
create index if not exists tier_member_candidates_found_at_idx
  on public.tier_member_candidates (found_at desc);
create index if not exists tier_member_candidates_status_idx
  on public.tier_member_candidates (status);

alter table public.tier_member_candidates enable row level security;

-- Internal pipeline table. Browser clients do not need access.
revoke all on table public.tier_member_candidates from anon, authenticated;
grant select, insert, update, delete on table public.tier_member_candidates to service_role;


-- ############################################################################
-- 3. EloBoard 수집 보강
-- ############################################################################

-- ststat Part 3: EloBoard collection hardening.
-- Safe to run more than once. Existing StarUniv elo_* tables are reused.

create index if not exists elo_matches_date_idx on public.elo_matches (match_date desc);
create index if not exists elo_matches_winner_idx on public.elo_matches (winner_elo_id);
create index if not exists elo_matches_loser_idx on public.elo_matches (loser_elo_id);
create index if not exists elo_matches_map_idx on public.elo_matches (map_id);
create index if not exists elo_matches_category_idx on public.elo_matches (category_id);
create index if not exists elo_players_name_idx on public.elo_players (name);

-- Pipeline writes these tables with the service role. Browser write access is unnecessary.
alter table public.elo_categories enable row level security;
alter table public.elo_maps enable row level security;
alter table public.elo_players enable row level security;
alter table public.elo_matches enable row level security;

grant select, insert, update, delete on table public.elo_categories to service_role;
grant select, insert, update, delete on table public.elo_maps to service_role;
grant select, insert, update, delete on table public.elo_players to service_role;
grant select, insert, update, delete on table public.elo_matches to service_role;


-- ############################################################################
-- 4. EloBoard 파생 통계(스냅샷 교체)
-- ############################################################################

-- ststat Part 4: EloBoard derived statistics.
-- Safe-swap design: ststat writes a complete new snapshot, validates it, then activates it
-- with one transactional RPC. The previously active snapshot stays readable until activation.

create extension if not exists pgcrypto;

create table if not exists public.elo_derived_snapshots (
  snapshot_id uuid primary key default gen_random_uuid(),
  as_of date not null,
  status text not null default 'building' check (status in ('building','active','retired','failed')),
  source_match_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  activated_at timestamptz
);
create unique index if not exists elo_derived_one_active_uq
  on public.elo_derived_snapshots ((status)) where status = 'active';

create table if not exists public.elo_player_stats (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  total_games integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  win_rate numeric(7,4),
  last_match_date date,
  primary key (snapshot_id, elo_id)
);
create index if not exists elo_player_stats_elo_idx on public.elo_player_stats(elo_id);

create table if not exists public.elo_h2h_stats (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  player_elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  opponent_elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  games integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  win_rate numeric(7,4),
  last_match_date date,
  primary key (snapshot_id, player_elo_id, opponent_elo_id)
);
create index if not exists elo_h2h_stats_player_idx on public.elo_h2h_stats(player_elo_id);
create index if not exists elo_h2h_stats_opponent_idx on public.elo_h2h_stats(opponent_elo_id);

create table if not exists public.elo_race_stats (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  opponent_race text not null,
  games integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  win_rate numeric(7,4),
  primary key (snapshot_id, elo_id, opponent_race)
);
create index if not exists elo_race_stats_elo_idx on public.elo_race_stats(elo_id);

create table if not exists public.elo_rankings (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  tier text,
  tier_rank integer,
  tier_count integer,
  raw_rating numeric(10,3),
  rating numeric(10,3),
  data_tier text,
  tier_gap integer,
  recent_365_games integer not null default 0,
  recent_365_wins integer not null default 0,
  recent_90_games integer not null default 0,
  recent_90_wins integer not null default 0,
  recent_30_games integer not null default 0,
  recent_30_wins integer not null default 0,
  as_of date not null,
  primary key (snapshot_id, elo_id)
);
create index if not exists elo_rankings_tier_rank_idx on public.elo_rankings(tier, tier_rank);
create index if not exists elo_rankings_elo_idx on public.elo_rankings(elo_id);

create table if not exists public.elo_ranking_meta (
  snapshot_id uuid primary key references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  as_of date not null,
  half_life_days integer not null,
  half_life_tier_days integer not null,
  recent_days integer not null,
  min_recent_games integer not null,
  tier_counts jsonb not null default '{}'::jsonb,
  tier_levels jsonb not null default '{}'::jsonb
);

create table if not exists public.elo_rating_history (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  month_end date not null,
  rating numeric(10,3),
  primary key (snapshot_id, elo_id, month_end)
);
create index if not exists elo_rating_history_elo_idx on public.elo_rating_history(elo_id, month_end);

-- Detailed directional match view; no duplicated match storage.
create or replace view public.elo_player_matches as
select m.elo_match_id, m.match_date, m.winner_elo_id as elo_id,
       m.loser_elo_id as opponent_elo_id, true as won, m.map_id, m.category_id
from public.elo_matches m
union all
select m.elo_match_id, m.match_date, m.loser_elo_id as elo_id,
       m.winner_elo_id as opponent_elo_id, false as won, m.map_id, m.category_id
from public.elo_matches m;

-- Atomic pointer swap after a complete snapshot was inserted.
create or replace function public.activate_elo_derived_snapshot(p_snapshot uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.elo_derived_snapshots
    where snapshot_id = p_snapshot and status = 'building'
  ) then
    raise exception 'snapshot % is not in building state', p_snapshot;
  end if;

  update public.elo_derived_snapshots
     set status = 'retired'
   where status = 'active';

  update public.elo_derived_snapshots
     set status = 'active', activated_at = now()
   where snapshot_id = p_snapshot;
end;
$$;
revoke all on function public.activate_elo_derived_snapshot(uuid) from public, anon, authenticated;
grant execute on function public.activate_elo_derived_snapshot(uuid) to service_role;

-- Public readers can only see rows belonging to the active snapshot.
alter table public.elo_derived_snapshots enable row level security;
alter table public.elo_player_stats enable row level security;
alter table public.elo_h2h_stats enable row level security;
alter table public.elo_race_stats enable row level security;
alter table public.elo_rankings enable row level security;
alter table public.elo_ranking_meta enable row level security;
alter table public.elo_rating_history enable row level security;

create or replace function public.is_active_elo_snapshot(p_snapshot uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.elo_derived_snapshots s where s.snapshot_id=p_snapshot and s.status='active') $$;
revoke all on function public.is_active_elo_snapshot(uuid) from public;
grant execute on function public.is_active_elo_snapshot(uuid) to anon, authenticated, service_role;

do $$
declare t text;
begin
  drop policy if exists elo_derived_snapshots_public_read on public.elo_derived_snapshots;
  create policy elo_derived_snapshots_public_read on public.elo_derived_snapshots
    for select to anon, authenticated using (status='active');

  foreach t in array array['elo_player_stats','elo_h2h_stats','elo_race_stats','elo_rankings','elo_ranking_meta','elo_rating_history'] loop
    execute format('drop policy if exists %I on public.%I', t || '_public_read', t);
    execute format('create policy %I on public.%I for select to anon, authenticated using (public.is_active_elo_snapshot(snapshot_id))', t || '_public_read', t);
  end loop;
end $$;

grant select on public.elo_derived_snapshots, public.elo_player_stats, public.elo_h2h_stats,
  public.elo_race_stats, public.elo_rankings, public.elo_ranking_meta, public.elo_rating_history to anon, authenticated;
grant select on public.elo_player_matches to anon, authenticated;


-- ############################################################################
-- 5. 시너지 월간·일별 방송 통계
-- ############################################################################

-- Part 5: Synergy monthly live stats + daily snapshots.
-- Safe to run more than once.

create table if not exists public.poonggo_monthly_stats (
  month_start date not null,
  soop_id text not null,
  balloons bigint not null default 0,
  broadcast_seconds bigint not null default 0,
  cumulative_viewers bigint not null default 0,
  fetched_at timestamptz not null default now(),
  primary key (month_start, soop_id)
);
create index if not exists poonggo_monthly_stats_soop_idx
  on public.poonggo_monthly_stats (soop_id, month_start desc);

create table if not exists public.daily_member_stats (
  stat_date date not null,
  month_start date not null,
  soop_id text not null,
  elo_id integer,
  nickname text not null,
  role text not null default '',
  affiliation text,
  race text,
  tier text,
  gender text,
  birth_date date,
  balloons bigint not null default 0,
  broadcast_seconds bigint not null default 0,
  cumulative_viewers bigint not null default 0,
  sponsor_wins integer not null default 0,
  sponsor_losses integer not null default 0,
  updated_at timestamptz not null default now(),
  sponsor_updated_at timestamptz,
  primary key (stat_date, soop_id)
);
create index if not exists daily_member_stats_soop_date_idx
  on public.daily_member_stats (soop_id, stat_date desc);
create index if not exists daily_member_stats_date_idx
  on public.daily_member_stats (stat_date desc);
create index if not exists daily_member_stats_affiliation_idx
  on public.daily_member_stats (affiliation, stat_date desc);
create index if not exists daily_member_stats_elo_idx
  on public.daily_member_stats (elo_id, stat_date desc);

create table if not exists public.synergy_month_confirmations (
  month_start date primary key,
  poonggo_complete boolean not null default false,
  sponsor_complete boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.poonggo_monthly_stats enable row level security;
alter table public.daily_member_stats enable row level security;
alter table public.synergy_month_confirmations enable row level security;

-- No anon policy yet. During Part 5 these are pipeline validation tables.
-- Service role used by ststat bypasses RLS. Synergy public read is enabled in the web cutover phase.


-- ############################################################################
-- 6. 영상 수집
-- ############################################################################

-- ststat Part 6: video collection ownership/support
-- Existing StarUniv video tables are reused. Safe to re-run.

create table if not exists public.video_channels (
  channel_url text primary key,
  channel_id text,
  title text,
  display_name text,
  thumb text,
  uploads text,
  source_order integer not null unique,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id text primary key,
  channel_url text,
  title text not null,
  published timestamptz,
  thumb text,
  views bigint not null default 0,
  short boolean not null default false,
  hidden boolean not null default false,
  updated_at timestamptz not null default now()
);

create index if not exists videos_published_idx on public.videos (published desc);
create index if not exists videos_channel_idx on public.videos (channel_url);
create index if not exists videos_channel_published_idx on public.videos (channel_url, published desc);

comment on table public.videos is
  'Automatic video collection is owned by ststat; videos.hidden remains admin-owned.';

comment on table public.video_channels is
  'Admin owns channel_url/display_name/source_order/active. ststat owns channel_id/title/thumb/uploads metadata.';


-- ############################################################################
-- 7. 경기·라운드 연결 점검
-- ############################################################################

-- ststat Part 7
-- Match/round linking is already authoritative in Supabase:
--   rounds.match_no -> matches.match_no
-- Therefore the old heuristic match_link.py must NOT be ported as a writer.
--
-- This section adds a canonical read-only view that reproduces the only
-- still-useful derived behavior from match_link.py: mirrored internal rounds.

create or replace view public.rounds_effective
with (security_invoker = true)
as
select
  r.id as source_round_id,
  false as is_mirrored,
  r.source_order,
  r.match_no,
  r.match_date,
  r.opponent_team,
  r.match_format,
  r.set_name,
  r.round_name,
  r.our_player,
  r.our_race,
  r.our_tier,
  r.result,
  r.opponent_player,
  r.opponent_race,
  r.opponent_tier,
  r.map_name
from public.rounds r

union all

select
  r.id as source_round_id,
  true as is_mirrored,
  r.source_order,
  r.match_no,
  r.match_date,
  r.opponent_team,
  r.match_format,
  r.set_name,
  r.round_name,
  r.opponent_player as our_player,
  r.opponent_race as our_race,
  r.opponent_tier as our_tier,
  case
    when r.result = '승' then '패'
    when r.result = '패' then '승'
    else r.result
  end as result,
  r.our_player as opponent_player,
  coalesce(
    nullif(r.our_race, ''),
    case
      when coalesce(m.race, '') like '%테란%' then 'T'
      when coalesce(m.race, '') like '%저그%' then 'Z'
      when coalesce(m.race, '') like '%프로토스%' then 'P'
      else ''
    end
  ) as opponent_race,
  r.our_tier as opponent_tier,
  r.map_name
from public.rounds r
left join public.members m
  on m.nickname = r.our_player
where trim(coalesce(r.opponent_team, '')) = '내전'
  and trim(coalesce(r.our_player, '')) <> ''
  and trim(coalesce(r.opponent_player, '')) <> '';

comment on view public.rounds_effective is
  'Read-only canonical rounds view. Includes one mirrored row for each internal round; base public.rounds is never duplicated or rewritten.';

-- Intentionally no anonymous grant yet.
-- StarUniv still uses its current frontend fallback during validation.


-- ############################################################################
-- 8. 시너지 하루치 한 번에 게시
-- ############################################################################

-- Publish a complete Synergy day in one database transaction.
-- Apply before deploying the matching ststat job.

alter table public.daily_member_stats
  add column if not exists gender text,
  add column if not exists birth_date date;

create or replace function public.publish_daily_member_stats(
  p_stat_date date,
  p_rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_distinct integer;
begin
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    raise exception 'daily snapshot rows must be a non-empty array';
  end if;

  -- Serialize publishers for the same date. Readers continue to see the old
  -- complete day until this transaction commits.
  perform pg_advisory_xact_lock(hashtext('daily_member_stats:' || p_stat_date::text));

  select count(*), count(distinct x.soop_id)
    into v_count, v_distinct
    from jsonb_to_recordset(p_rows) as x(stat_date date, soop_id text);

  if v_count <> v_distinct then
    raise exception 'daily snapshot contains duplicate soop_id values';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(p_rows) as x(stat_date date)
    where x.stat_date is distinct from p_stat_date
  ) then
    raise exception 'daily snapshot contains a different stat_date';
  end if;

  delete from public.daily_member_stats where stat_date = p_stat_date;

  insert into public.daily_member_stats (
    stat_date, month_start, soop_id, elo_id, nickname, role, affiliation,
    race, tier, gender, birth_date, balloons, broadcast_seconds,
    cumulative_viewers, sponsor_wins, sponsor_losses, updated_at,
    sponsor_updated_at
  )
  select
    x.stat_date, x.month_start, x.soop_id, x.elo_id, x.nickname,
    coalesce(x.role, ''), x.affiliation, x.race, x.tier, x.gender,
    x.birth_date, coalesce(x.balloons, 0),
    coalesce(x.broadcast_seconds, 0), coalesce(x.cumulative_viewers, 0),
    coalesce(x.sponsor_wins, 0), coalesce(x.sponsor_losses, 0),
    coalesce(x.updated_at, now()), x.sponsor_updated_at
  from jsonb_to_recordset(p_rows) as x(
    stat_date date,
    month_start date,
    soop_id text,
    elo_id integer,
    nickname text,
    role text,
    affiliation text,
    race text,
    tier text,
    gender text,
    birth_date date,
    balloons bigint,
    broadcast_seconds bigint,
    cumulative_viewers bigint,
    sponsor_wins integer,
    sponsor_losses integer,
    updated_at timestamptz,
    sponsor_updated_at timestamptz
  );

  get diagnostics v_count = row_count;
  if v_count <> jsonb_array_length(p_rows) then
    raise exception 'daily snapshot row count mismatch: inserted %, expected %',
      v_count, jsonb_array_length(p_rows);
  end if;
  return v_count;
end;
$$;

revoke all on function public.publish_daily_member_stats(date, jsonb) from public, anon, authenticated;
grant execute on function public.publish_daily_member_stats(date, jsonb) to service_role;


-- ############################################################################
-- 9. StarUniv·Synergy 공개 조회
-- ############################################################################

-- Public read contract used by StarUniv and Synergy browsers.
-- Schema changes live in ststat so the two web repositories only consume them.

create or replace view public.elo_public_players
as
select
  p.elo_id,
  p.name as elo_name,
  coalesce(nullif(tm.race,''), p.race, '') as race,
  tm.nickname,
  tm.soop_id,
  tm.tier,
  tm.affiliation,
  ps.total_games,
  ps.wins,
  ps.last_match_date,
  rk.tier_rank,
  rk.tier_count,
  s.as_of
from public.elo_players p
join public.elo_derived_snapshots s on s.status='active'
left join public.tier_members tm on tm.elo_id=p.elo_id
left join public.elo_player_stats ps on ps.snapshot_id=s.snapshot_id and ps.elo_id=p.elo_id
left join public.elo_rankings rk on rk.snapshot_id=s.snapshot_id and rk.elo_id=p.elo_id;

create or replace view public.elo_public_matches
as
select
  pm.elo_match_id,
  pm.match_date,
  pm.elo_id,
  pm.opponent_elo_id,
  pm.won,
  pm.map_id,
  mp.name as map_name,
  c.name as category_name
from public.elo_player_matches pm
left join public.elo_maps mp on mp.map_id=pm.map_id
left join public.elo_categories c on c.category_id=pm.category_id;

grant select on public.elo_public_players, public.elo_public_matches to anon, authenticated;

alter table public.daily_member_stats enable row level security;
drop policy if exists synergy_daily_public_read on public.daily_member_stats;
create policy synergy_daily_public_read on public.daily_member_stats
for select to anon, authenticated using (true);
grant select on public.daily_member_stats to anon, authenticated;

create or replace view public.synergy_daily_dates
with (security_invoker = true)
as
select stat_date, max(updated_at) as updated_at
from public.daily_member_stats
group by stat_date
order by stat_date desc;

grant select on public.synergy_daily_dates to anon, authenticated;


-- ############################################################################
-- 10. 티어랭킹 v4(모든 선수 레이팅·종족 상성)
-- ############################################################################

-- ststat ranking v4: 모든 선수의 레이팅(θ)·표준오차와 종족 상성을 공개한다.
--
-- elo_rankings는 순위에 오른 선수(티어 있음 · 최근 1년 10판 이상 · 휴면 아님)만 담는다.
-- 엔트리 예상승률은 순위 밖 선수에게도 티어 평균이 아닌 실제 추정치를 써야 하므로
-- 맞춘 모든 선수의 θ를 따로 둔다. 값은 Elo 점수 단위(1500 기준, 400/ln10 배율).
--
-- 적용 순서: 이 마이그레이션을 먼저 적용한 뒤 ranking v4 파이프라인 코드를 배포한다
-- (코드가 elo_player_ratings에 쓰고 elo_ranking_meta.race_matchup을 넣는다).

create table if not exists public.elo_player_ratings (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  rating numeric(10,3) not null,
  rating_se numeric(10,3),
  as_of date not null,
  primary key (snapshot_id, elo_id)
);
create index if not exists elo_player_ratings_elo_idx on public.elo_player_ratings(elo_id);

-- 종족 상성(Elo 점수): {"TZ": 테란의 저그 상대 우위, "ZP": 저그→프로토스, "PT": 프로토스→테란}
alter table public.elo_ranking_meta
  add column if not exists race_matchup jsonb not null default '{}'::jsonb;

alter table public.elo_player_ratings enable row level security;
drop policy if exists elo_player_ratings_public_read on public.elo_player_ratings;
create policy elo_player_ratings_public_read on public.elo_player_ratings
  for select to anon, authenticated using (public.is_active_elo_snapshot(snapshot_id));
grant select on public.elo_player_ratings to anon, authenticated;


-- ############################################################################
-- 11. 어드민 운영 현황
-- ############################################################################

-- admin_dashboard_stats가 elo_matches 전체를 count(*)·min·max 한 번에 훑어서, 경기가 쌓이자
-- 로그인 사용자 statement_timeout(기본 8초)에 걸려 어드민 운영 현황이 "조회 실패"가 됐다.
--  - 경기 수: 통계 추정치(pg_class.reltuples, ANALYZE 때 갱신). 화면에 "약"으로 표시.
--  - ID·날짜 범위: 인덱스 끝값만 읽는 order by … limit 1.
--  - 방송통계 갱신 시각: 최신 날짜 행만 본다.
-- 반환 모양은 010과 같고 elo.total_estimated만 더했다. 여러 번 실행해도 된다.
create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  elo_total bigint;
  daily_date date;
  job_name text;
  job_status text;
  job_finished timestamptz;
begin
  if not public.is_admin() then
    raise exception 'admin access required' using errcode = '42501';
  end if;

  select greatest(c.reltuples, 0)::bigint into elo_total
    from pg_class c where c.oid = 'public.elo_matches'::regclass;
  select stat_date into daily_date
    from public.daily_member_stats order by stat_date desc limit 1;
  select s.job_name, s.status, s.finished_at
    into job_name, job_status, job_finished
    from public.sync_jobs s order by s.started_at desc limit 1;

  select jsonb_build_object(
    'counts', jsonb_build_object(
      'members', (select count(*) from public.members),
      'teams', (select count(*) from public.teams),
      'matches', (select count(*) from public.matches),
      'tier_members', (select count(*) from public.tier_members),
      'calendar_events', (select count(*) from public.calendar_events),
      'calendar_off_air', (select count(*) from public.calendar_off_air),
      'video_channels', (select count(*) from public.video_channels),
      'videos', (select count(*) from public.videos),
      'video_picks', (select count(*) from public.video_picks),
      'external_tools', (select count(*) from public.external_tools),
      'elo_players', (select count(*) from public.elo_players),
      'elo_matches', elo_total
    ),
    'elo', jsonb_build_object(
      'total', elo_total,
      'total_estimated', true,
      'min_match_id', (select elo_match_id from public.elo_matches order by elo_match_id asc limit 1),
      'max_match_id', (select elo_match_id from public.elo_matches order by elo_match_id desc limit 1),
      'first_match_date', (select match_date from public.elo_matches order by match_date asc limit 1),
      'last_match_date', (select match_date from public.elo_matches order by match_date desc limit 1)
    ),
    'freshness', jsonb_build_object(
      'daily_stat_date', daily_date,
      'daily_updated_at', (select max(updated_at) from public.daily_member_stats where stat_date = daily_date),
      'elo_as_of', (select as_of from public.elo_derived_snapshots where status='active' limit 1),
      'elo_activated_at', (select activated_at from public.elo_derived_snapshots where status='active' limit 1),
      'last_job_name', job_name,
      'last_job_status', job_status,
      'last_job_finished_at', job_finished
    )
  ) into result;
  return result;
end;
$$;

revoke all on function public.admin_dashboard_stats() from public;
grant execute on function public.admin_dashboard_stats() to authenticated;
