-- ststat Supabase 전체 설정. SQL 편집기에 통째로 붙여 넣고 실행한다(여러 번 실행해도 되고 운영 데이터는 안 바꾼다).
-- staruniv 저장소의 supabase/staruniv.sql(기본 표·is_admin 등)을 먼저 실행한다.


-- ############################################################################
-- 1. 작업 기록(sync_jobs)
-- ############################################################################

create table if not exists public.sync_jobs (
    id bigint generated by default as identity primary key,
    job_name text not null,
    run_id text,
    status text not null check (status in ('running','success','failed','skipped')),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    records_read integer not null default 0,
    records_written integer not null default 0,
    records_skipped integer not null default 0,
    error_message text,
    source_cursor text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists sync_jobs_job_name_started_idx
on public.sync_jobs (job_name, started_at desc);

alter table public.sync_jobs enable row level security;

-- 내부 기록이라 정책을 두지 않는다(service role만 쓴다).


-- ############################################################################
-- 2. 선수 후보 대기열(tier_member_candidates)
-- ############################################################################

create table if not exists public.tier_member_candidates (
  id text primary key,
  nickname text not null default '',
  elo_id integer,
  gender text,
  race text,
  tier text,
  affiliation text,
  source text,
  found_at date,
  status text not null default 'pending',
  last_seen_at date,
  -- EloBoard의 SOOP ID는 틀릴 때가 있어 참고용이다(같은 사람 판별은 ELO ID).
  soop_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- id는 'elo:<ELO ID>'다(SOOP ID로 하면 같은 사람이 두 줄이 되거나 명단에 있는데도 신규로 뜬다).

create index if not exists tier_member_candidates_elo_id_idx
  on public.tier_member_candidates (elo_id);
create index if not exists tier_member_candidates_found_at_idx
  on public.tier_member_candidates (found_at desc);
create index if not exists tier_member_candidates_status_idx
  on public.tier_member_candidates (status);

alter table public.tier_member_candidates enable row level security;

revoke all on table public.tier_member_candidates from anon, authenticated;
grant select, insert, update, delete on table public.tier_member_candidates to service_role;
grant select, update, delete on table public.tier_member_candidates to authenticated;
drop policy if exists tier_member_candidates_admin on public.tier_member_candidates;
create policy tier_member_candidates_admin on public.tier_member_candidates
  for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));


-- ############################################################################
-- 3. EloBoard 수집 보강
-- ############################################################################

-- elo_* 표·RLS는 staruniv.sql 1번이 만든다. 여기에는 service role 쓰기 권한만 둔다.

grant select, insert, update, delete on table public.elo_categories to service_role;
grant select, insert, update, delete on table public.elo_maps to service_role;
grant select, insert, update, delete on table public.elo_players to service_role;
grant select, insert, update, delete on table public.elo_matches to service_role;


-- ############################################################################
-- 4. EloBoard 파생 통계(스냅샷 교체)
-- ############################################################################

-- 새 스냅샷을 다 쓴 뒤 한 트랜잭션으로 활성으로 바꾼다(그전까지는 이전 스냅샷을 읽는다).

create extension if not exists pgcrypto;

create table if not exists public.elo_derived_snapshots (
  snapshot_id uuid primary key default gen_random_uuid(),
  as_of date not null,
  status text not null default 'building' check (status in ('building','active','retired','failed')),
  source_match_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  activated_at timestamptz
);
create unique index if not exists elo_derived_one_active_uq
  on public.elo_derived_snapshots ((status)) where status = 'active';

create table if not exists public.elo_player_stats (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  total_games integer not null default 0,
  wins integer not null default 0,
  last_match_date date,
  primary key (snapshot_id, elo_id)
);
create index if not exists elo_player_stats_elo_idx on public.elo_player_stats(elo_id);

create table if not exists public.elo_rankings (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  tier text,
  tier_rank integer,
  tier_count integer,
  raw_rating numeric(10,3),
  data_tier text,
  tier_gap integer,
  recent_365_games integer not null default 0,
  recent_365_wins integer not null default 0,
  recent_90_games integer not null default 0,
  recent_90_wins integer not null default 0,
  recent_30_games integer not null default 0,
  recent_30_wins integer not null default 0,
  as_of date not null,
  primary key (snapshot_id, elo_id)
);
create index if not exists elo_rankings_tier_rank_idx on public.elo_rankings(tier, tier_rank);
create index if not exists elo_rankings_elo_idx on public.elo_rankings(elo_id);

create table if not exists public.elo_ranking_meta (
  snapshot_id uuid primary key references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  as_of date not null,
  half_life_days integer not null,
  half_life_tier_days integer not null,
  recent_days integer not null,
  min_recent_games integer not null,
  tier_counts jsonb not null default '{}'::jsonb,
  tier_levels jsonb not null default '{}'::jsonb
);

create table if not exists public.elo_rating_history (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  month_end date not null,
  rating numeric(10,3),
  primary key (snapshot_id, elo_id, month_end)
);
create index if not exists elo_rating_history_elo_idx on public.elo_rating_history(elo_id, month_end);

-- 경기 한 줄을 승자·패자 쪽 두 줄로 펼친다.
create or replace view public.elo_player_matches as
select m.elo_match_id, m.match_date, m.winner_elo_id as elo_id,
       m.loser_elo_id as opponent_elo_id, true as won, m.map_id, m.category_id
from public.elo_matches m
union all
select m.elo_match_id, m.match_date, m.loser_elo_id as elo_id,
       m.winner_elo_id as opponent_elo_id, false as won, m.map_id, m.category_id
from public.elo_matches m;

create or replace function public.activate_elo_derived_snapshot(p_snapshot uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.elo_derived_snapshots
    where snapshot_id = p_snapshot and status = 'building'
  ) then
    raise exception 'snapshot % is not in building state', p_snapshot;
  end if;

  update public.elo_derived_snapshots
     set status = 'retired'
   where status = 'active';

  update public.elo_derived_snapshots
     set status = 'active', activated_at = now()
   where snapshot_id = p_snapshot;
end;
$$;
revoke all on function public.activate_elo_derived_snapshot(uuid) from public, anon, authenticated;
grant execute on function public.activate_elo_derived_snapshot(uuid) to service_role;

-- 로그인 사용자는 활성 스냅샷 행만 본다. anon은 14번 공개 읽기 함수로만 받는다.
alter table public.elo_derived_snapshots enable row level security;
alter table public.elo_player_stats enable row level security;
alter table public.elo_rankings enable row level security;
alter table public.elo_ranking_meta enable row level security;
alter table public.elo_rating_history enable row level security;

-- 정책에서는 (select …)로 감싸 조회당 한 번만 계산되게 한다(행마다 부르면 수십만 번 불린다).
create or replace function public.active_elo_snapshot_id()
returns uuid language sql stable security definer set search_path=public
as $$ select snapshot_id from public.elo_derived_snapshots where status='active' limit 1 $$;
revoke all on function public.active_elo_snapshot_id() from public;
grant execute on function public.active_elo_snapshot_id() to authenticated, service_role;

do $$
declare t text;
begin
  drop policy if exists elo_derived_snapshots_public_read on public.elo_derived_snapshots;
  create policy elo_derived_snapshots_public_read on public.elo_derived_snapshots
    for select to authenticated using (status='active');

  foreach t in array array['elo_player_stats','elo_rankings','elo_ranking_meta','elo_rating_history'] loop
    execute format('drop policy if exists %I on public.%I', t || '_public_read', t);
    execute format('create policy %I on public.%I for select to authenticated using (snapshot_id = (select public.active_elo_snapshot_id()))', t || '_public_read', t);
  end loop;
end $$;

grant select on public.elo_derived_snapshots, public.elo_player_stats,
  public.elo_rankings, public.elo_ranking_meta, public.elo_rating_history to authenticated;
grant select on public.elo_player_matches to authenticated;

-- 파생 계산 입력의 지문: 활성 스냅샷 것과 같으면 calculate_eloboard_stats가 다시 계산하지 않는다(egress 절약).
-- 행 해시의 합이라 순서와 무관하다.
create or replace function public.elo_derived_source_signature()
returns text
language sql
stable
set search_path = public
as $$
  select concat_ws(':',
    (select count(*) || '/' || coalesce(sum(hashtextextended(r::text, 0)::numeric), 0)
       from (select elo_match_id, match_date, winner_elo_id, loser_elo_id, map_id, category_id
               from public.elo_matches) r),
    (select count(*) || '/' || coalesce(sum(hashtextextended(r::text, 0)::numeric), 0)
       from (select elo_id, name, race from public.elo_players) r),
    (select count(*) || '/' || coalesce(sum(hashtextextended(r::text, 0)::numeric), 0)
       from (select category_id, name from public.elo_categories) r),
    (select count(*) || '/' || coalesce(sum(hashtextextended(r::text, 0)::numeric), 0)
       from (select elo_id, nickname, name, soop_id, tier, affiliation, race, tier_table_registered,
                    promoted_tier_0, promoted_tier_1, promoted_tier_2, promoted_tier_3, promoted_tier_4,
                    promoted_tier_5, promoted_tier_6, promoted_tier_7, promoted_tier_8
               from public.tier_members) r)
  );
$$;
revoke all on function public.elo_derived_source_signature() from public, anon, authenticated;
grant execute on function public.elo_derived_source_signature() to service_role;

-- 다시 받은 경기는 대부분 그대로라 기존 행과 다른 것만 쓰고 바꾼 수를 돌려준다.
create or replace function public.upsert_elo_batch(p_players jsonb, p_maps jsonb, p_matches jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  n_players integer;
  n_maps integer;
  n_matches integer;
begin
  insert into public.elo_players as t (elo_id, name, race)
  -- 종족 표기를 맞춰 비교한다(안 맞추면 T와 테란이 달라 보여 매번 모든 선수를 다시 쓴다)
  select distinct on (r.elo_id) r.elo_id, r.name, public.normalize_race(r.race)
  from jsonb_to_recordset(coalesce(p_players, '[]'::jsonb)) as r(elo_id integer, name text, race text)
  where r.elo_id is not null and r.name is not null
  on conflict (elo_id) do update set name = excluded.name, race = excluded.race
    where (t.name, t.race) is distinct from (excluded.name, excluded.race);
  get diagnostics n_players = row_count;

  insert into public.elo_maps as t (map_id, name)
  select distinct on (r.map_id) r.map_id, r.name
  from jsonb_to_recordset(coalesce(p_maps, '[]'::jsonb)) as r(map_id integer, name text)
  where r.map_id is not null and r.name is not null
  on conflict (map_id) do update set name = excluded.name
    where t.name is distinct from excluded.name;
  get diagnostics n_maps = row_count;

  insert into public.elo_matches as t (elo_match_id, match_date, winner_elo_id, loser_elo_id, map_id, category_id)
  select distinct on (r.elo_match_id) r.elo_match_id, r.match_date, r.winner_elo_id, r.loser_elo_id, r.map_id, r.category_id
  from jsonb_to_recordset(coalesce(p_matches, '[]'::jsonb)) as r(
    elo_match_id bigint, match_date date, winner_elo_id integer, loser_elo_id integer, map_id integer, category_id smallint)
  where r.elo_match_id is not null
  on conflict (elo_match_id) do update
    set match_date = excluded.match_date, winner_elo_id = excluded.winner_elo_id, loser_elo_id = excluded.loser_elo_id,
        map_id = excluded.map_id, category_id = excluded.category_id
    where (t.match_date, t.winner_elo_id, t.loser_elo_id, t.map_id, t.category_id)
      is distinct from (excluded.match_date, excluded.winner_elo_id, excluded.loser_elo_id, excluded.map_id, excluded.category_id);
  get diagnostics n_matches = row_count;

  return jsonb_build_object('players', n_players, 'maps', n_maps, 'matches', n_matches);
end;
$$;

revoke all on function public.upsert_elo_batch(jsonb, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.upsert_elo_batch(jsonb, jsonb, jsonb) to service_role;

-- 파생 계산용: (p_after, p_upto] 경기를 배열 하나로 준다(표 직접 읽기의 1000행 제한·열 이름 반복을 피한다).
create or replace function public.elo_matches_compact(p_after bigint, p_upto bigint)
returns json
language sql
stable
set search_path = public
as $$
  select coalesce(json_agg(json_build_array(elo_match_id, match_date, winner_elo_id, loser_elo_id,
                                            map_id, category_id) order by elo_match_id), '[]'::json)
    from public.elo_matches
   where elo_match_id > p_after and elo_match_id <= p_upto;
$$;
revoke all on function public.elo_matches_compact(bigint, bigint) from public, anon, authenticated;
grant execute on function public.elo_matches_compact(bigint, bigint) to service_role;


-- ############################################################################
-- 5. 시너지 월간·일별 방송 통계
-- ############################################################################

create table if not exists public.poonggo_monthly_stats (
  month_start date not null,
  soop_id text not null,
  balloons bigint not null default 0,
  broadcast_seconds bigint not null default 0,
  cumulative_viewers bigint not null default 0,
  fetched_at timestamptz not null default now(),
  primary key (month_start, soop_id)
);
-- 출처는 트래키파이(예비 풍고, 표 이름은 그대로). 뷰어십(시청자 수 × 방송 초)은 트래키파이만 줘서 풍고 달은 null.
alter table public.poonggo_monthly_stats add column if not exists viewership_seconds bigint;
create index if not exists poonggo_monthly_stats_soop_idx
  on public.poonggo_monthly_stats (soop_id, month_start desc);

create table if not exists public.daily_member_stats (
  stat_date date not null,
  month_start date not null,
  soop_id text not null,
  elo_id integer,
  nickname text not null,
  role text not null default '',
  affiliation text,
  race text,
  tier text,
  gender text,
  birth_date date,
  balloons bigint not null default 0,
  broadcast_seconds bigint not null default 0,
  cumulative_viewers bigint not null default 0,
  sponsor_wins integer not null default 0,
  sponsor_losses integer not null default 0,
  updated_at timestamptz not null default now(),
  sponsor_updated_at timestamptz,
  primary key (stat_date, soop_id)
);
-- 뷰어십이 null인 날은 사이트가 뷰어십 지표를 숨긴다.
alter table public.daily_member_stats add column if not exists viewership_seconds bigint;
-- 목록 🎂 표시에는 생년월일 대신 생일 달만 공개한다.
alter table public.daily_member_stats add column if not exists birth_month smallint
  generated always as (extract(month from birth_date)::smallint) stored;
create index if not exists daily_member_stats_soop_date_idx
  on public.daily_member_stats (soop_id, stat_date desc);
create index if not exists daily_member_stats_date_idx
  on public.daily_member_stats (stat_date desc);
create index if not exists daily_member_stats_affiliation_idx
  on public.daily_member_stats (affiliation, stat_date desc);
create index if not exists daily_member_stats_elo_idx
  on public.daily_member_stats (elo_id, stat_date desc);

create table if not exists public.synergy_month_confirmations (
  month_start date primary key,
  poonggo_complete boolean not null default false,
  sponsor_complete boolean not null default false,
  updated_at timestamptz not null default now()
);

-- 트래키파이 월간 요약에서 빠진 방송을 관리자가 표 편집기로 넣는다(시각은 KST). 파이프라인이 방송시간·뷰어십에
-- 더하고, 게시된 날은 applied_through까지 한 번만 더한다. 트래키파이가 고치면 줄을 지운다(두 번 더해진다).
create table if not exists public.missing_broadcasts (
  id bigint generated always as identity primary key,
  soop_id text not null,
  broad_no text,
  started_at timestamp not null,
  ended_at timestamp not null check (ended_at > started_at),
  avg_viewers integer not null check (avg_viewers >= 0),
  note text,
  applied_through date,
  created_at timestamptz not null default now()
);

alter table public.poonggo_monthly_stats enable row level security;
alter table public.daily_member_stats enable row level security;
alter table public.synergy_month_confirmations enable row level security;
alter table public.missing_broadcasts enable row level security;
revoke all on table public.missing_broadcasts from anon, authenticated;
grant select, insert, update, delete on table public.missing_broadcasts to service_role;


-- ############################################################################
-- 6. 영상 수집
-- ############################################################################

-- 영상 표·정책은 staruniv.sql 1·2번. 열 소유는 config/ownership.yml video_collection.

create index if not exists videos_channel_published_idx on public.videos (channel_url, published desc);

comment on table public.videos is
  'Automatic video collection is owned by ststat; videos.hidden remains admin-owned.';

comment on table public.video_channels is
  'Admin owns channel_url/display_name/source_order/active. ststat owns channel_id/title/thumb/uploads metadata.';


-- ############################################################################
-- 7. 경기·라운드 연결 점검
-- ############################################################################

-- 내전 라운드는 양쪽 선수 시점으로 보도록 뒤집은 줄을 하나 더한다.

create or replace view public.rounds_effective
with (security_invoker = true)
as
select
  r.id as source_round_id,
  false as is_mirrored,
  r.source_order,
  r.match_no,
  r.match_date,
  r.opponent_team,
  r.match_format,
  r.set_name,
  r.round_name,
  r.our_player,
  r.our_race,
  r.our_tier,
  r.result,
  r.opponent_player,
  r.opponent_race,
  r.opponent_tier,
  r.map_name
from public.rounds r

union all

select
  r.id as source_round_id,
  true as is_mirrored,
  r.source_order,
  r.match_no,
  r.match_date,
  r.opponent_team,
  r.match_format,
  r.set_name,
  r.round_name,
  r.opponent_player as our_player,
  r.opponent_race as our_race,
  r.opponent_tier as our_tier,
  case
    when r.result = '승' then '패'
    when r.result = '패' then '승'
    else r.result
  end as result,
  r.our_player as opponent_player,
  coalesce(
    nullif(r.our_race, ''),
    case
      when coalesce(m.race, '') like '%테란%' then 'T'
      when coalesce(m.race, '') like '%저그%' then 'Z'
      when coalesce(m.race, '') like '%프로토스%' then 'P'
      else ''
    end
  ) as opponent_race,
  r.our_tier as opponent_tier,
  r.map_name
from public.rounds r
left join public.members m
  on m.nickname = r.our_player
where trim(coalesce(r.opponent_team, '')) = '내전'
  and trim(coalesce(r.our_player, '')) <> ''
  and trim(coalesce(r.opponent_player, '')) <> '';

comment on view public.rounds_effective is
  'Read-only canonical rounds view. Includes one mirrored row for each internal round; base public.rounds is never duplicated or rewritten.';


-- ############################################################################
-- 8. 시너지 하루치 한 번에 게시
-- ############################################################################

create or replace function public.publish_daily_member_stats(
  p_stat_date date,
  p_rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_distinct integer;
begin
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    raise exception 'daily snapshot rows must be a non-empty array';
  end if;

  -- 같은 날짜의 동시 게시를 막는다.
  perform pg_advisory_xact_lock(hashtext('daily_member_stats:' || p_stat_date::text));

  select count(*), count(distinct x.soop_id)
    into v_count, v_distinct
    from jsonb_to_recordset(p_rows) as x(stat_date date, soop_id text);

  if v_count <> v_distinct then
    raise exception 'daily snapshot contains duplicate soop_id values';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(p_rows) as x(stat_date date)
    where x.stat_date is distinct from p_stat_date
  ) then
    raise exception 'daily snapshot contains a different stat_date';
  end if;

  delete from public.daily_member_stats where stat_date = p_stat_date;

  insert into public.daily_member_stats (
    stat_date, month_start, soop_id, elo_id, nickname, role, affiliation,
    race, tier, gender, birth_date, balloons, broadcast_seconds,
    cumulative_viewers, viewership_seconds, sponsor_wins, sponsor_losses, updated_at,
    sponsor_updated_at
  )
  select
    x.stat_date, x.month_start, x.soop_id, x.elo_id, x.nickname,
    coalesce(x.role, ''), x.affiliation, public.normalize_race(x.race), public.normalize_tier(x.tier), x.gender,
    x.birth_date, coalesce(x.balloons, 0),
    coalesce(x.broadcast_seconds, 0), coalesce(x.cumulative_viewers, 0), x.viewership_seconds,
    coalesce(x.sponsor_wins, 0), coalesce(x.sponsor_losses, 0),
    coalesce(x.updated_at, now()), x.sponsor_updated_at
  from jsonb_to_recordset(p_rows) as x(
    stat_date date,
    month_start date,
    soop_id text,
    elo_id integer,
    nickname text,
    role text,
    affiliation text,
    race text,
    tier text,
    gender text,
    birth_date date,
    balloons bigint,
    broadcast_seconds bigint,
    cumulative_viewers bigint,
    viewership_seconds bigint,
    sponsor_wins integer,
    sponsor_losses integer,
    updated_at timestamptz,
    sponsor_updated_at timestamptz
  );

  get diagnostics v_count = row_count;
  if v_count <> jsonb_array_length(p_rows) then
    raise exception 'daily snapshot row count mismatch: inserted %, expected %',
      v_count, jsonb_array_length(p_rows);
  end if;
  return v_count;
end;
$$;

revoke all on function public.publish_daily_member_stats(date, jsonb) from public, anon, authenticated;
grant execute on function public.publish_daily_member_stats(date, jsonb) to service_role;


-- ############################################################################
-- 9. StarUniv·Synergy 공개 조회
-- ############################################################################


create or replace view public.elo_public_players
as
select
  p.elo_id,
  p.name as elo_name,
  coalesce(nullif(tm.race,''), p.race, '') as race,
  tm.nickname,
  -- 휴면 선수도 검색 화면에 나오므로 프로필 사진용 SOOP ID를 준다
  tm.soop_id,
  tm.tier,
  tm.affiliation,
  ps.total_games,
  ps.wins,
  ps.last_match_date,
  rk.tier_rank,
  rk.tier_count,
  s.as_of
from public.elo_players p
join public.elo_derived_snapshots s on s.status='active'
left join public.tier_members tm on tm.elo_id=p.elo_id
left join public.elo_player_stats ps on ps.snapshot_id=s.snapshot_id and ps.elo_id=p.elo_id
left join public.elo_rankings rk on rk.snapshot_id=s.snapshot_id and rk.elo_id=p.elo_id;

create or replace view public.elo_public_matches
as
select
  pm.elo_match_id,
  pm.match_date,
  pm.elo_id,
  pm.opponent_elo_id,
  pm.won,
  pm.map_id,
  mp.name as map_name,
  c.name as category_name
from public.elo_player_matches pm
left join public.elo_maps mp on mp.map_id=pm.map_id
left join public.elo_categories c on c.category_id=pm.category_id;

grant select on public.elo_public_players, public.elo_public_matches to authenticated;

drop policy if exists synergy_daily_admin_read on public.daily_member_stats;
-- 표를 직접 읽는 것은 관리자만(생일·성별 보호). 공개는 14번 함수와 player_* 함수로만.
create policy synergy_daily_admin_read on public.daily_member_stats
for select to authenticated using ((select public.is_admin()));
grant select on public.daily_member_stats to authenticated;

create or replace view public.synergy_daily_dates
with (security_invoker = true)
as
select stat_date, max(updated_at) as updated_at
from public.daily_member_stats
group by stat_date
order by stat_date desc;

grant select on public.synergy_daily_dates to authenticated;

-- 선수를 지정한 조회는 휴면이어도 준다. security definer라 화면에 나오는 열만 돌려준다. 날짜를 비우면 최근 날짜.
-- 반환 칸이 바뀌면 create or replace가 안 되므로 지우고 다시 만든다(권한은 아래에서 다시 준다).
-- StarUniv 방송통계·멤버 프로필: 쉼표로 구분한 SOOP ID(최대 300개)의 수치만
drop function if exists public.player_stats(text, date);
create function public.player_stats(p_ids text, p_date date default null)
returns table (stat_date date, soop_id text, nickname text, balloons bigint, broadcast_seconds bigint,
               cumulative_viewers bigint, sponsor_wins integer, sponsor_losses integer, updated_at timestamptz,
               viewership_seconds bigint)
language sql
stable
security definer
set search_path = public
as $$
  select s.stat_date, s.soop_id, s.nickname, s.balloons, s.broadcast_seconds, s.cumulative_viewers,
         s.sponsor_wins, s.sponsor_losses, s.updated_at, s.viewership_seconds
  from public.daily_member_stats s
  where s.stat_date = coalesce(p_date, (select max(x.stat_date) from public.daily_member_stats x))
    and lower(s.soop_id) in (select lower(btrim(i)) from unnest((string_to_array(coalesce(p_ids, ''), ','))[1:300]) i
                             where btrim(i) <> '')
  order by s.soop_id;
$$;

-- 시너지 개인 프로필: 한 명의 프로필 칸
drop function if exists public.player_profile_stats(text, date);
create function public.player_profile_stats(p_soop_id text, p_date date default null)
returns table (stat_date date, soop_id text, nickname text, role text, affiliation text, race text, tier text,
               gender text, birth_date date, balloons bigint, broadcast_seconds bigint, cumulative_viewers bigint,
               sponsor_wins integer, sponsor_losses integer, updated_at timestamptz, sponsor_updated_at timestamptz,
               viewership_seconds bigint)
language sql
stable
security definer
set search_path = public
as $$
  select s.stat_date, s.soop_id, s.nickname, s.role, s.affiliation, s.race, s.tier, s.gender, s.birth_date,
         s.balloons, s.broadcast_seconds, s.cumulative_viewers, s.sponsor_wins, s.sponsor_losses,
         s.updated_at, s.sponsor_updated_at, s.viewership_seconds
  from public.daily_member_stats s
  where s.stat_date = coalesce(p_date, (select max(x.stat_date) from public.daily_member_stats x))
    and lower(s.soop_id) = lower(btrim(coalesce(p_soop_id, '')))
  limit 1;
$$;

revoke all on function public.player_stats(text, date) from public;
revoke all on function public.player_profile_stats(text, date) from public;
grant execute on function public.player_stats(text, date) to anon, authenticated;
grant execute on function public.player_profile_stats(text, date) to anon, authenticated;


-- ############################################################################
-- 10. 모든 선수 레이팅·종족 상성
-- ############################################################################

-- elo_rankings는 순위 대상만 담으므로, 엔트리 예상승률용으로 모든 선수의 θ·표준오차를 둔다(Elo 단위, 1500 기준).

create table if not exists public.elo_player_ratings (
  snapshot_id uuid not null references public.elo_derived_snapshots(snapshot_id) on delete cascade,
  elo_id integer not null references public.elo_players(elo_id) on delete cascade,
  rating numeric(10,3) not null,
  rating_se numeric(10,3),
  as_of date not null,
  primary key (snapshot_id, elo_id)
);
create index if not exists elo_player_ratings_elo_idx on public.elo_player_ratings(elo_id);

-- 종족 상성(Elo 점수): {"TZ": 테란의 저그 상대 우위, "ZP": 저그→프로토스, "PT": 프로토스→테란}
alter table public.elo_ranking_meta
  add column if not exists race_matchup jsonb not null default '{}'::jsonb;

alter table public.elo_player_ratings enable row level security;
drop policy if exists elo_player_ratings_public_read on public.elo_player_ratings;
create policy elo_player_ratings_public_read on public.elo_player_ratings
  for select to authenticated using (snapshot_id = (select public.active_elo_snapshot_id()));
grant select on public.elo_player_ratings to authenticated;


-- ############################################################################
-- 11. 어드민 운영 현황
-- ############################################################################

-- elo_matches를 훑으면 statement_timeout(8초)에 걸리므로 경기 수는 reltuples 추정치, 범위는 인덱스 끝값만 읽는다.
create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  elo_total bigint;
  daily_date date;
  job_name text;
  job_status text;
  job_finished timestamptz;
begin
  if not public.is_admin() then
    raise exception 'admin access required' using errcode = '42501';
  end if;

  select greatest(c.reltuples, 0)::bigint into elo_total
    from pg_class c where c.oid = 'public.elo_matches'::regclass;
  select stat_date into daily_date
    from public.daily_member_stats order by stat_date desc limit 1;
  select s.job_name, s.status, s.finished_at
    into job_name, job_status, job_finished
    from public.sync_jobs s order by s.started_at desc limit 1;

  select jsonb_build_object(
    'counts', jsonb_build_object(
      'members', (select count(*) from public.members),
      'teams', (select count(*) from public.teams),
      'matches', (select count(*) from public.matches),
      'tier_members', (select count(*) from public.tier_members),
      'calendar_events', (select count(*) from public.calendar_events),
      'calendar_off_air', (select count(*) from public.calendar_off_air),
      'video_channels', (select count(*) from public.video_channels),
      'videos', (select count(*) from public.videos),
      'video_picks', (select count(*) from public.video_picks),
      'external_tools', (select count(*) from public.external_tools),
      'elo_players', (select count(*) from public.elo_players),
      'elo_matches', elo_total
    ),
    'elo', jsonb_build_object(
      'total', elo_total,
      'total_estimated', true,
      'min_match_id', (select elo_match_id from public.elo_matches order by elo_match_id asc limit 1),
      'max_match_id', (select elo_match_id from public.elo_matches order by elo_match_id desc limit 1),
      'first_match_date', (select match_date from public.elo_matches order by match_date asc limit 1),
      'last_match_date', (select match_date from public.elo_matches order by match_date desc limit 1)
    ),
    'freshness', jsonb_build_object(
      'daily_stat_date', daily_date,
      'daily_updated_at', (select max(updated_at) from public.daily_member_stats where stat_date = daily_date),
      'elo_as_of', (select as_of from public.elo_derived_snapshots where status='active' limit 1),
      'elo_activated_at', (select activated_at from public.elo_derived_snapshots where status='active' limit 1),
      'last_job_name', job_name,
      'last_job_status', job_status,
      'last_job_finished_at', job_finished
    )
  ) into result;
  return result;
end;
$$;

revoke all on function public.admin_dashboard_stats() from public;
grant execute on function public.admin_dashboard_stats() to authenticated;


-- ############################################################################
-- 12. 방송 중 표시(라이브)
-- ############################################################################
-- Edge Function live-status가 채운다. 읽기 함수는 5분 안에 갱신된 행만 줘서 수집이 멈추면 전부 '방송 안 함'이 된다.

create table if not exists public.live_broadcasts (
    soop_id text primary key,
    broad_no text,
    broad_title text,
    current_sum_viewer integer,
    broad_start text,
    category_name text,
    broad_cate_no text,
    scanned_at timestamptz not null default now()
);

alter table public.live_broadcasts enable row level security;
drop policy if exists live_broadcasts_public_read on public.live_broadcasts;
-- 수집은 휴면 포함 명단 전원, 공개는 휴면 아닌 선수만.
create policy live_broadcasts_public_read on public.live_broadcasts
for select to authenticated using (
  exists (select 1 from public.tier_members tm
          where tm.soop_id = live_broadcasts.soop_id and coalesce(tm.affiliation, '') <> '휴면')
);
grant select on table public.live_broadcasts to authenticated;
grant select, insert, update, delete on table public.live_broadcasts to service_role;

-- 시너지 개인 프로필의 방송 중 표시(휴면 포함)
create or replace function public.player_live(p_soop_id text)
returns table (broad_no text, broad_title text, current_sum_viewer integer, broad_start text)
language sql
stable
security definer
set search_path = public
as $$
  select b.broad_no, b.broad_title, b.current_sum_viewer, b.broad_start
  from public.live_broadcasts b
  where lower(b.soop_id) = lower(btrim(coalesce(p_soop_id, '')))
    and b.scanned_at > now() - interval '5 minutes'
  limit 1;
$$;
revoke all on function public.player_live(text) from public;
grant execute on function public.player_live(text) to anon, authenticated;

-- 수집 상태 한 줄
create table if not exists public.live_scan_state (
    id smallint primary key check (id = 1),
    started_at timestamptz,
    finished_at timestamptz,
    last_ok_at timestamptz,
    info jsonb not null default '{}'::jsonb,
    last_error text
);

alter table public.live_scan_state enable row level security;
grant select, insert, update on table public.live_scan_state to service_role;

-- 50초 안에 다른 수집이 시작됐으면 false(SOOP에 요청이 몰리지 않게).
create or replace function public.try_begin_live_scan()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  ok boolean;
begin
  insert into public.live_scan_state (id) values (1) on conflict (id) do nothing;
  update public.live_scan_state
     set started_at = now()
   where id = 1
     and (started_at is null or started_at < now() - interval '50 seconds')
  returning true into ok;
  return coalesce(ok, false);
end;
$$;

-- 명단 전체를 내려받지 않고 겹치는 아이디만 돌려준다(2분마다 도는 수집의 egress 절약).
create or replace function public.live_roster_match(p_ids text[])
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'roster', (select count(distinct btrim(t.soop_id)) from public.tier_members t
                where btrim(coalesce(t.soop_id, '')) <> ''),
    'ids', coalesce((select jsonb_agg(distinct btrim(t.soop_id)) from public.tier_members t
                      where btrim(t.soop_id) = any(p_ids)), '[]'::jsonb)
  );
$$;

-- 한 트랜잭션이라 읽는 쪽이 빈 표를 보지 않는다.
create or replace function public.replace_live_broadcasts(p_rows jsonb, p_info jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  n integer;
begin
  delete from public.live_broadcasts where true;
  insert into public.live_broadcasts
    (soop_id, broad_no, broad_title, current_sum_viewer, broad_start, category_name, broad_cate_no, scanned_at)
  select r.soop_id, r.broad_no, r.broad_title, r.current_sum_viewer, r.broad_start, r.category_name, r.broad_cate_no, now()
  from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb)) as r(
    soop_id text, broad_no text, broad_title text, current_sum_viewer integer,
    broad_start text, category_name text, broad_cate_no text)
  where coalesce(r.soop_id, '') <> ''
  on conflict (soop_id) do nothing;
  get diagnostics n = row_count;
  update public.live_scan_state
     set finished_at = now(), last_ok_at = now(), info = coalesce(p_info, '{}'::jsonb), last_error = null
   where id = 1;
  return n;
end;
$$;

-- 실패는 기록만 하고 표는 그대로 둔다.
create or replace function public.fail_live_scan(p_error text, p_info jsonb)
returns void
language sql
security definer
set search_path = public
as $$
  update public.live_scan_state
     set finished_at = now(), last_error = p_error, info = coalesce(p_info, '{}'::jsonb)
   where id = 1;
$$;

revoke all on function public.try_begin_live_scan() from public, anon, authenticated;
revoke all on function public.live_roster_match(text[]) from public, anon, authenticated;
revoke all on function public.replace_live_broadcasts(jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.fail_live_scan(text, jsonb) from public, anon, authenticated;
grant execute on function public.try_begin_live_scan() to service_role;
grant execute on function public.live_roster_match(text[]) to service_role;
grant execute on function public.replace_live_broadcasts(jsonb, jsonb) to service_role;
grant execute on function public.fail_live_scan(text, jsonb) to service_role;

-- pg_cron이 2분마다 Edge Function을 부른다(다시 실행해도 예약은 하나).
create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;
select cron.unschedule(jobid) from cron.job where jobname in ('live-status', 'live-status-log-cleanup');
select cron.schedule('live-status', '*/2 * * * *', $cron$
  select net.http_post(
    url := 'https://czqxedrayvgxirvlveon.supabase.co/functions/v1/live-status',
    body := '{}'::jsonb,
    timeout_milliseconds := 60000
  );
$cron$);
-- 실행 기록이 하루 720줄씩 쌓이므로 3일 지난 것은 지운다
select cron.schedule('live-status-log-cleanup', '17 4 * * *', $cron$
  delete from cron.job_run_details where end_time < now() - interval '3 days';
$cron$);


-- ############################################################################
-- 13. 멤버 공지 모음(member_posts)
-- ############################################################################
-- 활동 멤버의 SOOP 게시판 첫 쪽(본인 글만). live-status가 2분마다 채운다(2쪽부터는 사이트가 SOOP에 직접 묻는다).
-- reg_date는 SOOP 문자열("YYYY-MM-DD HH:MM:SS", KST) 그대로라 글자순이 곧 시간순이다.

create table if not exists public.member_posts (
  soop_id text not null,
  title_no bigint not null,
  reg_date text,
  total_pages integer not null default 1,
  post jsonb not null,
  scanned_at timestamptz not null default now(),
  primary key (soop_id, title_no)
);
create index if not exists member_posts_reg_date_idx on public.member_posts (reg_date desc);

alter table public.member_posts enable row level security;
drop policy if exists member_posts_public_read on public.member_posts;
create policy member_posts_public_read on public.member_posts
for select to authenticated using (true);
grant select on table public.member_posts to authenticated;
grant select, insert, update, delete on table public.member_posts to service_role;

-- 달라진 글만 쓰고, 받은 멤버의 첫 쪽에서 사라진 글과 활동 명단(p_active)에서 빠진 멤버의 글만 지운다.
-- 못 받은 멤버의 글은 그대로 둔다(일시 오류로 사라지지 않게). 모은 시각은 posts_scanned_at에 적는다
-- (글 행의 scanned_at은 그 글이 바뀐 시각).
alter table public.live_scan_state add column if not exists posts_scanned_at timestamptz;

create or replace function public.replace_member_posts(p_rows jsonb, p_scanned text[], p_active text[])
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  n_del integer;
  n_up integer;
begin
  drop table if exists _mp_new;   -- 같은 트랜잭션에서 두 번 불려도 되게
  create temp table _mp_new on commit drop as
  select lower(r.soop_id) as sid, r.soop_id, r.title_no, r.reg_date, coalesce(r.total_pages, 1) as total_pages, r.post
  from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb)) as r(
    soop_id text, title_no bigint, reg_date text, total_pages integer, post jsonb)
  where coalesce(r.soop_id, '') <> '' and r.title_no is not null;

  delete from public.member_posts m
   where not (lower(m.soop_id) = any (select lower(x) from unnest(coalesce(p_active, '{}')) x))
      or (lower(m.soop_id) = any (select lower(x) from unnest(coalesce(p_scanned, '{}')) x)
          and not exists (select 1 from _mp_new n where n.sid = lower(m.soop_id) and n.title_no = m.title_no));
  get diagnostics n_del = row_count;

  insert into public.member_posts as m (soop_id, title_no, reg_date, total_pages, post, scanned_at)
  select distinct on (n.soop_id, n.title_no) n.soop_id, n.title_no, n.reg_date, n.total_pages, n.post, now()
  from _mp_new n
  on conflict (soop_id, title_no) do update
    set reg_date = excluded.reg_date, total_pages = excluded.total_pages, post = excluded.post, scanned_at = now()
    where (m.reg_date, m.total_pages, m.post) is distinct from (excluded.reg_date, excluded.total_pages, excluded.post);
  get diagnostics n_up = row_count;

  insert into public.live_scan_state (id, posts_scanned_at) values (1, now())
  on conflict (id) do update set posts_scanned_at = excluded.posts_scanned_at;
  return n_del + n_up;
end;
$$;

revoke all on function public.replace_member_posts(jsonb, text[], text[]) from public, anon, authenticated;
grant execute on function public.replace_member_posts(jsonb, text[], text[]) to service_role;


-- ############################################################################
-- 14. 익명(anon) 공개 범위: 공개 읽기 함수로만
-- ############################################################################
-- Supabase는 public의 새 표·뷰에 anon 권한을 기본으로 주므로 전부 회수하고, 공개 범위(휴면 제외 등)는
-- 아래 공개 읽기 함수에서만 정한다. StarUniv 기본 표는 staruniv.sql 2번.
revoke all on public.elo_derived_snapshots, public.elo_player_stats,
  public.elo_rankings, public.elo_ranking_meta, public.elo_rating_history, public.elo_player_ratings,
  public.elo_player_matches, public.elo_public_players, public.elo_public_matches,
  public.elo_players, public.elo_matches, public.elo_maps, public.elo_categories,
  public.daily_member_stats, public.synergy_daily_dates,
  public.poonggo_monthly_stats, public.synergy_month_confirmations, public.live_broadcasts, public.live_scan_state, public.member_posts,
  public.rounds_effective, public.sync_jobs from anon;

-- 대학 로고는 어느 화면에든 나오는 대학만. 표는 staruniv.sql 6번.
create or replace function public.university_logo_shown(p_name text) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.tier_members where affiliation = p_name and affiliation <> '휴면')
      or exists (select 1 from public.matches where opponent_team = p_name)
      or exists (select 1 from public.daily_member_stats where affiliation = p_name and affiliation <> '휴면');
$$;
revoke all on function public.university_logo_shown(text) from public;

-- 공개 읽기 함수(/api/v1): StarUniv(api.js)·시너지(app.js)가 부르고, 함수 하나가 staruniv api/openapi.yaml 주소 하나다.
-- security definer라 표 정책을 거치지 않으므로 거르는 조건을 함수마다 적는다.
create or replace function public.api_university_logos(p_names jsonb) returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('name', l.name, 'path', l.path, 'color', l.color)), '[]'::json)
  from public.university_logos l
  where l.name in (select jsonb_array_elements_text(case when jsonb_typeof(p_names) = 'array' then p_names else '[]'::jsonb end))
    and public.university_logo_shown(l.name);
$$;

-- 시너지 대학 카드: 그날(비우면 휴면 아닌 행의 최근 날짜) 휴면 아닌 선수. p_light는 지난달 순위 증감용 지표 칸만.
create or replace function public.api_daily_stats(p_date date default null, p_light boolean default false) returns json
language sql stable security definer set search_path = public as $$
  with d as (
    select coalesce(p_date, (select max(stat_date) from public.daily_member_stats
                             where coalesce(affiliation, '') <> '휴면')) as day
  )
  select coalesce(json_agg(case when p_light
      then json_build_object('role', s.role, 'affiliation', s.affiliation, 'gender', s.gender, 'balloons', s.balloons,
        'broadcast_seconds', s.broadcast_seconds, 'cumulative_viewers', s.cumulative_viewers,
        'viewership_seconds', s.viewership_seconds, 'sponsor_wins', s.sponsor_wins, 'sponsor_losses', s.sponsor_losses)
      else json_build_object('stat_date', s.stat_date, 'soop_id', s.soop_id, 'nickname', s.nickname, 'role', s.role,
        'affiliation', s.affiliation, 'tier', s.tier, 'gender', s.gender, 'birth_month', s.birth_month,
        'balloons', s.balloons, 'broadcast_seconds', s.broadcast_seconds, 'cumulative_viewers', s.cumulative_viewers,
        'viewership_seconds', s.viewership_seconds,
        'sponsor_wins', s.sponsor_wins, 'sponsor_losses', s.sponsor_losses, 'updated_at', s.updated_at,
        'sponsor_updated_at', s.sponsor_updated_at) end
      order by case when p_light then null else s.nickname end, s.soop_id), '[]'::json)
  from public.daily_member_stats s, d
  where s.stat_date = d.day and coalesce(s.affiliation, '') <> '휴면';
$$;

-- 5분 안에 확인된 방송 중 휴면 아닌 선수만
create or replace function public.api_live() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('soop_id', b.soop_id, 'broad_no', b.broad_no, 'broad_title', b.broad_title,
      'current_sum_viewer', b.current_sum_viewer, 'broad_start', b.broad_start, 'category_name', b.category_name,
      'broad_cate_no', b.broad_cate_no)), '[]'::json)
  from public.live_broadcasts b
  where b.scanned_at > now() - interval '5 minutes'
    and exists (select 1 from public.tier_members tm
                where tm.soop_id = b.soop_id and coalesce(tm.affiliation, '') <> '휴면');
$$;

-- LIVE 점만 찍는 화면: 같은 범위의 SOOP ID만
create or replace function public.api_live_ids() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('soop_id', b.soop_id)), '[]'::json)
  from public.live_broadcasts b
  where b.scanned_at > now() - interval '5 minutes'
    and exists (select 1 from public.tier_members tm
                where tm.soop_id = b.soop_id and coalesce(tm.affiliation, '') <> '휴면');
$$;

-- 방송통계가 있는 날짜(최신순). 휴면 아닌 행이 있는 날만
create or replace function public.api_stats_dates() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('stat_date', d.stat_date) order by d.stat_date desc), '[]'::json)
  from (select distinct stat_date from public.daily_member_stats where coalesce(affiliation, '') <> '휴면') d;
$$;

-- 멤버 공지 모음(최신순 2000개)
create or replace function public.api_member_posts() returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('soop_id', p.soop_id, 'total_pages', p.total_pages, 'post', p.post)
      order by p.reg_date desc), '[]'::json)
  from (select * from public.member_posts order by reg_date desc limit 2000) p;
$$;

-- 홈 공지 카드: 최신 p_limit개(최대 50)의 제목·본문 글자·시각·첫 사진만
create or replace function public.api_recent_posts(p_limit integer default 6) returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('soop_id', p.soop_id, 'titleName', p.post->>'titleName',
      'regDate', p.post->>'regDate', 'text', p.post->'content'->>'textContent', 'thumb', p.post->'photos'->0->>'url')
      order by p.reg_date desc), '[]'::json)
  from (select * from public.member_posts order by reg_date desc
        limit least(greatest(coalesce(p_limit, 6), 1), 50)) p;
$$;

-- ELO 레이팅 기록이 있는 첫 달·마지막 달(활성 스냅샷)
create or replace function public.api_elo_rating_range() returns json
language sql stable security definer set search_path = public as $$
  select json_build_object('first', coalesce(min(month_end)::text, ''), 'last', coalesce(max(month_end)::text, ''))
  from public.elo_rating_history where snapshot_id = (select public.active_elo_snapshot_id());
$$;

-- 한 선수의 월말 레이팅(활성 스냅샷)
create or replace function public.api_elo_rating_history(p_elo_id integer) returns json
language sql stable security definer set search_path = public as $$
  select coalesce(json_agg(json_build_object('month_end', h.month_end, 'rating', h.rating) order by h.month_end), '[]'::json)
  from (select month_end, rating from public.elo_rating_history
        where snapshot_id = (select public.active_elo_snapshot_id()) and elo_id = p_elo_id
        order by month_end limit 1000) h;
$$;

-- 가장 최근 랭킹의 티어 기준선·종족 상성(활성 스냅샷, 없으면 {})
create or replace function public.api_elo_ranking_meta() returns json
language sql stable security definer set search_path = public as $$
  select coalesce((select json_build_object('as_of', as_of, 'tier_counts', tier_counts, 'tier_levels', tier_levels,
      'race_matchup', race_matchup)
    from public.elo_ranking_meta where snapshot_id = (select public.active_elo_snapshot_id())
    order by as_of desc limit 1), '{}'::json);
$$;

revoke all on function public.api_university_logos(jsonb), public.api_daily_stats(date, boolean), public.api_live(), public.api_live_ids(),
  public.api_stats_dates(), public.api_member_posts(), public.api_recent_posts(integer),
  public.api_elo_rating_range(), public.api_elo_rating_history(integer), public.api_elo_ranking_meta() from public;
grant execute on function public.api_university_logos(jsonb), public.api_daily_stats(date, boolean), public.api_live(), public.api_live_ids(),
  public.api_stats_dates(), public.api_member_posts(), public.api_recent_posts(integer),
  public.api_elo_rating_range(), public.api_elo_rating_history(integer), public.api_elo_ranking_meta() to anon, authenticated;

-- 긴 목록을 요청 한 번에 {"c": [열 이름], "r": [[값, …], …]}로 준다(StarUniv api.js가 객체 배열로 바꾼다).
-- 랭킹·레이팅은 활성 스냅샷만 거른다. elo_public_* 뷰는 정의 안에서 이미 거른다.
create or replace function public.elo_players_list(p_ranked boolean default false) returns json
language sql stable security definer set search_path = public as $$
  select json_build_object(
    'c', case when p_ranked
      then json_build_array('elo_id','elo_name','race','nickname','soop_id','tier','affiliation','total_games','tier_rank','tier_count','as_of')
      else json_build_array('elo_id','elo_name','race','nickname','soop_id','tier','affiliation','total_games') end,
    'r', coalesce((select json_agg(case when p_ranked
      then json_build_array(elo_id,elo_name,race,nickname,soop_id,tier,affiliation,total_games,tier_rank,tier_count,as_of)
      else json_build_array(elo_id,elo_name,race,nickname,soop_id,tier,affiliation,total_games) end order by elo_id)
      from public.elo_public_players), '[]'::json));
$$;
create or replace function public.elo_player_match_list(p_elo_id integer, p_since date default null) returns json
language sql stable security definer set search_path = public as $$
  select json_build_object(
    'c', json_build_array('match_date','opponent_elo_id','won','map_id','map_name','category_name'),
    'r', coalesce((select json_agg(json_build_array(match_date,opponent_elo_id,won,map_id,map_name,category_name) order by match_date desc)
      from public.elo_public_matches where elo_id = p_elo_id and (p_since is null or match_date >= p_since)), '[]'::json));
$$;
create or replace function public.elo_rankings_list() returns json
language sql stable security definer set search_path = public as $$
  select json_build_object(
    'c', json_build_array('elo_id','raw_rating','tier','tier_rank','as_of'),
    'r', coalesce((select json_agg(json_build_array(elo_id,raw_rating,tier,tier_rank,as_of) order by elo_id)
      from public.elo_rankings where snapshot_id = (select public.active_elo_snapshot_id())), '[]'::json));
$$;
create or replace function public.elo_player_ratings_list() returns json
language sql stable security definer set search_path = public as $$
  select json_build_object(
    'c', json_build_array('elo_id','rating','rating_se'),
    'r', coalesce((select json_agg(json_build_array(elo_id,rating,rating_se) order by elo_id)
      from public.elo_player_ratings where snapshot_id = (select public.active_elo_snapshot_id())), '[]'::json));
$$;
revoke all on function public.elo_players_list(boolean), public.elo_player_match_list(integer, date),
  public.elo_rankings_list(), public.elo_player_ratings_list() from public;
grant execute on function public.elo_players_list(boolean), public.elo_player_match_list(integer, date),
  public.elo_rankings_list(), public.elo_player_ratings_list() to anon, authenticated;


-- ############################################################################
-- 종족·티어 표기 통일 - 함수 normalize_race·normalize_tier는 staruniv.sql 10·11번
-- ############################################################################
-- 대기 명단은 출처마다 종족 표기(T/테란)가 달라 저장할 때 맞춘다(티어도).
create or replace function public.normalize_candidate_race()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.race := public.normalize_race(new.race);
  new.tier := public.normalize_tier(new.tier);
  return new;
end;
$$;
drop trigger if exists tier_member_candidates_normalize_race on public.tier_member_candidates;
create trigger tier_member_candidates_normalize_race before insert or update of race, tier on public.tier_member_candidates
  for each row execute function public.normalize_candidate_race();

-- 관리자 후보 삭제에 감사 기록을 붙인다(staruniv.sql과 어느 쪽을 먼저 실행해도 연결된다).
do $$
begin
  if to_regprocedure('public.audit_admin_delete()') is not null then
    drop trigger if exists admin_delete_audit on public.tier_member_candidates;
    create trigger admin_delete_audit after delete on public.tier_member_candidates
      for each row execute function public.audit_admin_delete('id');
  end if;
end;
$$;
