create table if not exists public.sync_jobs (
    id bigint generated by default as identity primary key,
    job_name text not null,
    run_id text,
    status text not null check (status in ('running','success','failed','skipped')),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    records_read integer not null default 0,
    records_written integer not null default 0,
    records_skipped integer not null default 0,
    error_message text,
    source_cursor text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists sync_jobs_job_name_started_idx
on public.sync_jobs (job_name, started_at desc);

alter table public.sync_jobs enable row level security;

-- sync_jobs is an internal operations table.
-- No anon/authenticated policies are created intentionally.
-- The ststat pipeline uses the Supabase service role key server-side only.
